/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexa
 */
public class graphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(graphique.class.getName());
    private int compteur;

    /**
     * Creates new form graphique
     */
    public graphique() {
        initComponents();
        zone_txt.setVisible(false);
        int compteur=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zone_txt = new javax.swing.JLabel();
        clicici = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zone_txt.setText("txt");
        getContentPane().add(zone_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 61, 160, -1));

        clicici.setBackground(new java.awt.Color(255, 0, 0));
        clicici.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clicici.setForeground(new java.awt.Color(204, 204, 255));
        clicici.setText("clicici");
        clicici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliciciActionPerformed(evt);
            }
        });
        getContentPane().add(clicici, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliciciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliciciActionPerformed
        // TODO add your handling code here
        zone_txt.setVisible(true);
        if (compteur==0)zone_txt.setText("Hello");
        if (compteur==1)zone_txt.setText("Rebonjour");
        if (compteur==2)zone_txt.setText("bon ça suffit");
        
        if (compteur==3)clicici.setEnabled(false);
        compteur++;
        
    }//GEN-LAST:event_cliciciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new graphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clicici;
    private javax.swing.JLabel zone_txt;
    // End of variables declaration//GEN-END:variables
}
