
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * Les textes des JButton pourront être définis dans l’interface au départ, mais
 * devront être changés dynamiquement en utilisant setText(...) dans le code. •
 * Vous devrez lire éventuellement le texte des boutons via getText() si vous
 * construisez votre logique dessus. • Vous devrez activer/désactiver les
 * boutons avec setEnabled(true/false) selon l’état du quiz (par exemple : après
 * une réponse, désactiver les boutons).
 *
 * @author alexa
 */
public class FenetreQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    private ArrayList<Question> listeQuestions = new ArrayList<>();
    private int scorequest = 0;

    private int indexQuestionCourante = 0;

    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }

    private void initialiserQuestions() {
        listeQuestions.add(new Question(
                "Quelle est la première loi de la thermodynamique ?",
                "L’énergie interne augmente spontanément",
                "La chaleur ne peut pas passer d’un corps froid à un corps chaud",
                "L’énergie se conserve : ΔU = Q – W",
                "La pression est inversement proportionnelle au volume",
                3
        ));

        listeQuestions.add(new Question(
                "Que reste-t-il constant lors d’une transformation isotherme ?",
                "La température",
                "La pression",
                "Le volume",
                "L’énergie interne",
                1
        ));

        listeQuestions.add(new Question(
                "Quelle relation décrit un gaz parfait ?",
                "P + V = T",
                "PV = nRT",
                "P = ρ g h",
                "T = k Q²",
                2
        ));

        listeQuestions.add(new Question(
                "Lors d’une compression adiabatique, que se passe-t-il ?",
                "La température reste constante",
                "Échange de chaleur avec l’extérieur",
                "La température augmente",
                "La pression reste constante",
                3
        ));

        listeQuestions.add(new Question(
                "Quelle grandeur correspond au désordre d’un système ?",
                "La chaleur",
                "L’énergie interne",
                "L’enthalpie",
                "L’entropie",
                4
        ));
    }

    private void afficherQuestionCourante() {

        Question q = listeQuestions.get(indexQuestionCourante);

        quest.setText("<html>" + q.getIntitule() + "</html>");

        btrep1.setText("<html>" + q.getProposition1() + "</html>");
        btrep2.setText("<html>" + q.getProposition2() + "</html>");
        btrep3.setText("<html>" + q.getProposition3() + "</html>");
        btrep4.setText("<html>" + q.getProposition4() + "</html>");

        btrep1.setEnabled(true);
        btrep2.setEnabled(true);
        btrep3.setEnabled(true);
        btrep4.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quest = new javax.swing.JLabel();
        btrep1 = new javax.swing.JButton();
        btrep2 = new javax.swing.JButton();
        btrep3 = new javax.swing.JButton();
        btrep4 = new javax.swing.JButton();
        nxtquest = new javax.swing.JButton();
        resultquest = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quest.setText("lblQuestion");
        getContentPane().add(quest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, 52));

        btrep1.setText("rep1");
        btrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btrep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 60));
        btrep1.getAccessibleContext().setAccessibleDescription("");

        btrep2.setText("rep2");
        btrep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btrep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 50));

        btrep3.setText("rep3");
        btrep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btrep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 193, 180, 50));

        btrep4.setText("rep4");
        btrep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btrep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 243, 180, 60));

        nxtquest.setText("prochainequestion");
        nxtquest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtquestActionPerformed(evt);
            }
        });
        getContentPane().add(nxtquest, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 160, 60));

        resultquest.setText("Resultatquestion");
        getContentPane().add(resultquest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 220, 130));

        score.setBackground(new java.awt.Color(204, 255, 204));
        score.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("score");
        score.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 51)));
        score.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrep1ActionPerformed
        // TODO add your handling code here:
        int numeroChoisi = 1; 
        Question q = listeQuestions.get(indexQuestionCourante);

        if (numeroChoisi == q.getIndexBonneReponse()) {
            resultquest.setText("<html>" + "Bonne réponse !" + "</html>");
            scorequest++;
            score.setText("<html>" + "Score : " + scorequest + "</html>");
        } else {
            resultquest.setText("<html>" + "Mauvaise réponse ! " + "</html>");
        }

        // désactiver les boutons
        btrep1.setEnabled(false);
        btrep2.setEnabled(false);
        btrep3.setEnabled(false);
        btrep4.setEnabled(false);

    }//GEN-LAST:event_btrep1ActionPerformed

    private void btrep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrep2ActionPerformed
        // TODO add your handling code here:
        int numeroChoisi = 2; 
        Question q = listeQuestions.get(indexQuestionCourante);

        if (numeroChoisi == q.getIndexBonneReponse()) {
            resultquest.setText("<html>" + "Bonne réponse !" + "</html>");
            scorequest++;
            score.setText("<html>" + "Score : " + scorequest + "</html>");
        } else {
            resultquest.setText("<html>" + "Mauvaise réponse !" + "</html>");
        }

        btrep1.setEnabled(false);
        btrep2.setEnabled(false);
        btrep3.setEnabled(false);
        btrep4.setEnabled(false);

    }//GEN-LAST:event_btrep2ActionPerformed

    private void btrep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrep4ActionPerformed
        // TODO add your handling code here:
        int numeroChoisi = 4;
        Question q = listeQuestions.get(indexQuestionCourante);

        if (numeroChoisi == q.getIndexBonneReponse()) {
            resultquest.setText("<html>" + "Bonne réponse !" + "</html>");
            scorequest++;
            score.setText("<html>" + "Score : " + scorequest + "</html>");
        } else {
            resultquest.setText("<html>" + "Mauvaise réponse !" + "</html>");
        }

        btrep1.setEnabled(false);
        btrep2.setEnabled(false);
        btrep3.setEnabled(false);
        btrep4.setEnabled(false);
    }//GEN-LAST:event_btrep4ActionPerformed

    private void btrep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrep3ActionPerformed
        // TODO add your handling code here:
        int numeroChoisi = 3;
        Question q = listeQuestions.get(indexQuestionCourante);

        if (numeroChoisi == q.getIndexBonneReponse()) {
            resultquest.setText("<html>" + "Bonne réponse !" + "</html>");
            scorequest++;
            score.setText("<html>" + "Score : " + scorequest + "</html>");
        } else {
            resultquest.setText("<html>" + "Mauvaise réponse !" + "</html>");
        }

        btrep1.setEnabled(false);
        btrep2.setEnabled(false);
        btrep3.setEnabled(false);
        btrep4.setEnabled(false);

    }//GEN-LAST:event_btrep3ActionPerformed

    private void nxtquestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtquestActionPerformed
        // TODO add your handling code here:
        indexQuestionCourante++;
        if (scorequest==5){
        Vic v=new Vic();
        v.setVisible(true);
        this.dispose();
        }
        if (indexQuestionCourante < listeQuestions.size()) {

            afficherQuestionCourante();

        } else {

            resultquest.setText("Quiz terminé. Score : " + scorequest + " / " + listeQuestions.size());

            nxtquest.setEnabled(false);

            btrep1.setEnabled(false);
            btrep2.setEnabled(false);
            btrep3.setEnabled(false);
            btrep4.setEnabled(false);
        }
    }//GEN-LAST:event_nxtquestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btrep1;
    private javax.swing.JButton btrep2;
    private javax.swing.JButton btrep3;
    private javax.swing.JButton btrep4;
    private javax.swing.JButton nxtquest;
    private javax.swing.JLabel quest;
    private javax.swing.JLabel resultquest;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
